export { getIsDocsLink } from './get-is-docs-link'
export { getIsLearnLink } from './get-is-learn-link'
export { getTutorialMap } from './get-tutorial-map'
export { handleCollectionLink } from './handle-collection-link'
export { handleDocsLink } from './handle-docs-link'
export { handleLearnLink } from './handle-learn-link'
export { handleTutorialLink } from './handle-tutorial-link'
