name: 'Build sitemap'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20

      - name: Build sitemaps
        run: npx hc-tools ./scripts/build-sitemap.ts
