name: Warm Developer Cache
on: [deployment_status]

jobs:
  cache:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'production' && github.event.sender.id == 35613825
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version-file: '.nvmrc'
      - name: Install npm@8
        run: npm install --global npm@8
      - name: Install dependencies
        run: npm ci
      - name: Cache .io sites, docs paths, and tutorial paths
        run: npx hc-tools ./scripts/warm-cache.ts
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
