name: Warm Developer Cache
on: [deployment_status]

jobs:
  cache:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'production' && github.event.sender.id == 35613825
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20
      - name: Install npm@8
        run: npm install --global npm@8
      - name: Install dependencies
        run: npm ci
      - name: Cache .io sites, docs paths, and tutorial paths
        run: npx hc-tools ./scripts/warm-cache.ts
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
