name: Warm Developer Cache
on: [deployment_status]

jobs:
  cache:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'production' && github.event.sender.id == 35613825
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 22
      - name: Install npm@8
        run: npm install --global npm@8
      - name: Install dependencies
        run: npm ci
      - name: Cache .io sites, docs paths, and tutorial paths
        run: npx hc-tools ./scripts/warm-cache.ts
        env:
          REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
