name: Cache .io & tutorial paths
on: [deployment_status]

jobs:
  cache:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'production' && github.event.sender.id == 35613825
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install npm@8
        run: npm install --global npm@8
      - name: Install dependencies
        run: npm ci
      - name: Cache .io sites and tutorial paths
        run: npx hc-tools ./scripts/warm-dotio-cache.ts
