name: DB Rutherford
on: [pull_request, workflow_dispatch]

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: debug
      run: echo "${{ toJSON(github) }}"

    - name: set the env.target value
      id: step_one
      run: echo "target=$((1 + $RANDOM % 4))" >> $GITHUB_ENV
  
    - name: print the env.target value
      id: step_two
      run: echo "${{ env.target }}"

    # if it's a hit, then add a comment
    - if: env.target == 1
      name: db rutherford leaves a comment
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          **DB Rutherford has something to say:** <test> 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        allow-repeats: false

    - if: env.target != '1'
      name: db rutherford sadly runs a noop
      run: echo "db rutherford says, it's a noop"