# Resources
#   - https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=labeled#pull_request
#   - https://docs.github.com/en/rest/pulls/pulls#list-pull-requests-files
#   - https://octokit.github.io/rest.js/v19#pulls-list-files

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'amb-super-temporary-label' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get list of PR files
        id: get-list-of-pr-files
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              pull_number: ${{ github.event.number }},
            })
            return data

      - name: Get list of changed MDX files
        id: get-list-of-changed-mdx-files
        uses: actions/github-script@v6
        env:
          ALL_PR_FILES: ${{ steps.get-list-of-pr-files.outputs.result }}
        with:
          script: |
            const changedMdxFiles = process.env.ALL_PR_FILES.filter((file) => {
              return file.status !== 'removed' && file.filename.endsWith('.mdx')
            })
            console.log('changedMdxFiles', changedMdxFiles)
