on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'amb-super-temporary-label' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello, world!"
