# Resources
#   - https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=labeled#pull_request
#   - https://octokit.github.io/rest.js/v19#pulls-list-files

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'amb-super-temporary-label' }}
    runs-on: ubuntu-latest

    steps:
      - name: List PR files
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.number }},
            })
            console.log(data)
