# Resources
#   - https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
#   - https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request
#   - https://octokit.github.io/rest.js/v19#pulls-list-files
#   - https://docs.github.com/en/rest/pulls/pulls#list-pull-requests-files
#   - https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OWNER: 'hashicorp'
      REPO: 'waypoint'
      FULL_REPO_NAME: 'hashicorp/waypoint'
      COMMIT_SHA: '058071ca8ffd22f206c68336c9ba345d1885a63d'
    steps:
      - name: Get PR number
        id: get-pr-number
        uses: actions/github-script@v6
        with:
          script: |
            // TODO don't hardcode owner, repo, commit_sha
            const { data } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: process.env.OWNER,
              repo: process.env.REPO,
              commit_sha: process.env.COMMIT_SHA
            })
            return data[0].number

      - name: Get list of PR files
        id: get-lists-of-pr-files
        uses: actions/github-script@v6
        env:
          PR_NUMBER: ${{ steps.get-pr-number.outputs.result }}
        with:
          script: |
            const changedMdxFiles = []
            const changedNavDataJsonFiles = []

            const { data: allPrFiles } = await github.rest.pulls.listFiles({
              owner: process.env.OWNER,
              repo: process.env.REPO,
              per_page: 100,
              pull_number: process.env.PR_NUMBER,
            })
            allPrFiles.forEach(file => {
              if (file.status === 'removed') {
                return
              }

              if (file.filename.endsWith('.mdx')) {
                changedMdxFiles.push(file.filename)
                return
              }

              if (file.filename.endsWith('-nav-data.json')) {
                changedNavDataJsonFiles.puhs(file.filename)
              }
            })

            const result = { changedMdxFiles, changedNavDataJsonFiles }
            console.log('get-lists-of-pr-files result:', result)
            return result

      - name: Check out branch with content changes
        uses: actions/checkout@v3
        with:
          repository: ${{ env.FULL_REPO_NAME }}
          ref: docs/amb.migrate-link-formats

      - name: Check files for legacy link formats
        id: check-files-for-legacy-link-formats
        uses: actions/github-script@v6
        env:
          RELEVANT_CHANGED_FILES: ${{ steps.get-lists-of-pr-files.outputs.result }}
        with:
          script: |
            const { RELEVANT_CHANGED_FILES } = process.env
            const { changedMdxFiles, changedNavDataJsonFiles } = JSON.parse(RELEVANT_CHANGED_FILES)
            console.log('changedMdxFiles', changedMdxFiles)
            console.log('changedNavDataJsonFiles', changedNavDataJsonFiles)
