# Resources
#   - https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
#   - https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request
#   - https://octokit.github.io/rest.js/v19#pulls-list-files
#   - https://docs.github.com/en/rest/pulls/pulls#list-pull-requests-files

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OWNER: 'hashicorp'
      REPO: 'waypoint'
      COMMIT_SHA: '058071ca8ffd22f206c68336c9ba345d1885a63d'
    steps:
      - name: Get PR number
        id: get-pr-number
        uses: actions/github-script@v6
        with:
          script: |
            // TODO don't hardcode owner, repo, commit_sha
            const { data } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: process.env.OWNER,
              repo: process.env.REPO,
              commit_sha: process.env.COMMIT_SHA
            })
            return data[0].number

      - name: Get list of PR files
        id: get-list-of-pr-files
        uses: actions/github-script@v6
        env:
          PR_NUMBER: ${{ steps.get-pr-number.outputs.result }}
        with:
          script: |
            const { data } = await github.rest.pulls.listFiles({
              owner: process.env.OWNER,
              repo: process.env.REPO,
              per_page: 100,
              pull_number: process.env.PR_NUMBER,
            })
            const result = data
            console.log('get-list-of-pr-files result:', result)
            return result

      - name: Get list of changed MDX files
        id: get-list-of-changed-mdx-files
        uses: actions/github-script@v6
        env:
          ALL_PR_FILES: ${{ steps.get-list-of-pr-files.outputs.result }}
        with:
          script: |
            const allPrFiles = JSON.parse(process.env.ALL_PR_FILES)
            const changedMdxFiles = allPrFiles.filter((file) => {
              return file.status !== 'removed' && file.filename.endsWith('.mdx')
            })
            const result = changedMdxFiles
            console.log('get-list-of-changed-mdx-files result:', result)
            return result

      - name: Get list of changed -nav-data.json files
        id: get-list-of-changed-nav-data-json-files
        uses: actions/github-script@v6
        env:
          ALL_PR_FILES: ${{ steps.get-list-of-pr-files.outputs.result }}
        with:
          script: |
            const allPrFiles = JSON.parse(process.env.ALL_PR_FILES)
            const changedNavDataJsonFiles = allPrFiles.filter((file) => {
              return file.status !== 'removed' && file.filename.endsWith('-nav-data.json')
            })
            const result = changedNavDataJsonFiles
            console.log('get-list-of-changed-nav-data-json-files result:', result)
            return result
            return changedNavDataJsonFiles
