on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'amb-super-temporary-label' }}
    runs-on: ubuntu-latest

    steps:
      - name: List PR files
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.pulls.listFiles({
              owner,
              repo,
              pull_number: ${{ github.event.number }},
            })
            console.log(data)
